server:
  port: 9400
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9200/eureka,http://LagouCloudEurekaServerB:9201/eureka
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinyunshaobing/lagou-config.git
          username: jinyunshaobing
          password: 199842160li
          search-paths:
            - lagou-config
      label: master